### ISSUE TITLE
Update `github.com/valyala/fasthttp` to version >=1.34.0

### ISSUE THREAD

**Issue by zroubalik** [dysnix/predictkube-libs#1]
There is a CVE on fasthttp: https://github.com/advisories/GHSA-fx95-883v-4q4h, `github.com/valyala/fasthttp` version >=1.34.0 should fix that. Please update this dependency so we can mitigate this in https://github.com/kedacore/keda/issues/2775

Thanks

**Comment by JorTurFer** [comment]
`github.com/fasthttp/router@v1.4.4` uses `github.com/valyala/fasthttp@v1.31.0` as dependency, could you bump it too?
